#ifndef SRC_DRIVER_HPP_
#define SRC_DRIVER_HPP_

#include <iostream>
#include <map>

#include "parser.hpp"  // generated by Bison

// Define the signature of yylex() to return a symbol_type instead of int.
// NOLINTNEXTLINE(runtime/references)
#define YY_DECL yy::Parser::symbol_type yylex(Driver& drv)
YY_DECL;

class Driver {
 public:
  int Parse();
};

#endif  // SRC_DRIVER_HPP_
